// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Intcode$Aoc19 = require("./Intcode.bs.js");
var Relude_Function = require("relude/src/Relude_Function.bs.js");
var InputLoader$Aoc19 = require("./lib/InputLoader.bs.js");
var StackSafeFuture$Aoc19 = require("./lib/StackSafeFuture.bs.js");

var $great$great = Relude_Function.Infix.$great$great;

var input = InputLoader$Aoc19.commaSeparated(5);

StackSafeFuture$Aoc19.map((function (eta) {
        return Intcode$Aoc19.run(undefined, undefined, eta);
      }), input);

exports.$great$great = $great$great;
exports.input = input;
/* input Not a pure module */
