// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Curry = require("bs-platform/lib/js/curry.js");
var Future = require("reason-future/src/Future.bs.js");
var Relude_String = require("relude/src/Relude_String.bs.js");

function loadDay(number) {
  var filename = __dirname + ("/input/day" + (String(number) + ".txt"));
  return Future.make((function (resolve) {
                Fs.readFile(filename, "utf-8", (function (param, data) {
                        return Curry._1(resolve, data);
                      }));
                return /* () */0;
              }));
}

function loadDayAsList(number) {
  return Future.map(loadDay(number), (function (param) {
                return Relude_String.splitList("\n", param);
              }));
}

exports.loadDay = loadDay;
exports.loadDayAsList = loadDayAsList;
/* fs Not a pure module */
