// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Future = require("reason-future/src/Future.bs.js");
var Readline = require("readline");

var defaultInput = {
  input: process.stdin,
  output: process.stdout
};

function make(param) {
  return Readline.createInterface(defaultInput);
}

function question(readline, query) {
  return Future.make((function (param) {
                readline.question(query, param);
                return /* () */0;
              }));
}

exports.defaultInput = defaultInput;
exports.make = make;
exports.question = question;
/* defaultInput Not a pure module */
