// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.bs.js");
var Day18$Aoc19 = require("../src/Day18.bs.js");

var mazeString = "#################\n#i.G..c...e..H.p#\n########.########\n#j.A..b...f..D.o#\n########@########\n#k.E..a...g..B.n#\n########.########\n#l.F..d...h..C.m#\n#################";

var maze = Day18$Aoc19.Maze.fromString(mazeString, false);

Jest.describe("local djikstras", (function (param) {
        Jest.test("collects all keys with none collected", (function (param) {
                return Jest.Expect.toEqual({
                            hd: [
                              "a",
                              3
                            ],
                            tl: {
                              hd: [
                                "b",
                                3
                              ],
                              tl: {
                                hd: [
                                  "f",
                                  3
                                ],
                                tl: {
                                  hd: [
                                    "g",
                                    3
                                  ],
                                  tl: {
                                    hd: [
                                      "c",
                                      5
                                    ],
                                    tl: {
                                      hd: [
                                        "d",
                                        5
                                      ],
                                      tl: {
                                        hd: [
                                          "e",
                                          5
                                        ],
                                        tl: {
                                          hd: [
                                            "h",
                                            5
                                          ],
                                          tl: /* [] */0
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }, Jest.Expect.expect(Day18$Aoc19.Maze.nextKeys(Day18$Aoc19.KeySet.empty, {
                                    TAG: /* Start */0,
                                    _0: 0
                                  }, maze)));
              }));
        Jest.test("ignores a collected key", (function (param) {
                return Jest.Expect.toEqual({
                            hd: [
                              "b",
                              3
                            ],
                            tl: {
                              hd: [
                                "f",
                                3
                              ],
                              tl: {
                                hd: [
                                  "g",
                                  3
                                ],
                                tl: {
                                  hd: [
                                    "c",
                                    5
                                  ],
                                  tl: {
                                    hd: [
                                      "d",
                                      5
                                    ],
                                    tl: {
                                      hd: [
                                        "e",
                                        5
                                      ],
                                      tl: {
                                        hd: [
                                          "h",
                                          5
                                        ],
                                        tl: /* [] */0
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }, Jest.Expect.expect(Day18$Aoc19.Maze.nextKeys(Day18$Aoc19.KeySet.fromList({
                                        hd: "a",
                                        tl: /* [] */0
                                      }), {
                                    TAG: /* Start */0,
                                    _0: 0
                                  }, maze)));
              }));
        Jest.test("collect through open door", (function (param) {
                return Jest.Expect.toEqual({
                            hd: [
                              "b",
                              3
                            ],
                            tl: {
                              hd: [
                                "f",
                                3
                              ],
                              tl: {
                                hd: [
                                  "g",
                                  3
                                ],
                                tl: {
                                  hd: [
                                    "c",
                                    5
                                  ],
                                  tl: {
                                    hd: [
                                      "d",
                                      5
                                    ],
                                    tl: {
                                      hd: [
                                        "h",
                                        5
                                      ],
                                      tl: {
                                        hd: [
                                          "k",
                                          8
                                        ],
                                        tl: /* [] */0
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }, Jest.Expect.expect(Day18$Aoc19.Maze.nextKeys(Day18$Aoc19.KeySet.fromList({
                                        hd: "a",
                                        tl: {
                                          hd: "e",
                                          tl: /* [] */0
                                        }
                                      }), {
                                    TAG: /* Start */0,
                                    _0: 0
                                  }, maze)));
              }));
        Jest.test("all near collected", (function (param) {
                return Jest.Expect.toEqual({
                            hd: [
                              "j",
                              8
                            ],
                            tl: {
                              hd: [
                                "k",
                                8
                              ],
                              tl: {
                                hd: [
                                  "n",
                                  8
                                ],
                                tl: {
                                  hd: [
                                    "o",
                                    8
                                  ],
                                  tl: {
                                    hd: [
                                      "i",
                                      10
                                    ],
                                    tl: {
                                      hd: [
                                        "l",
                                        10
                                      ],
                                      tl: {
                                        hd: [
                                          "m",
                                          10
                                        ],
                                        tl: {
                                          hd: [
                                            "p",
                                            10
                                          ],
                                          tl: /* [] */0
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }, Jest.Expect.expect(Day18$Aoc19.Maze.nextKeys(Day18$Aoc19.KeySet.fromList({
                                        hd: "a",
                                        tl: {
                                          hd: "b",
                                          tl: {
                                            hd: "c",
                                            tl: {
                                              hd: "d",
                                              tl: {
                                                hd: "e",
                                                tl: {
                                                  hd: "f",
                                                  tl: {
                                                    hd: "g",
                                                    tl: {
                                                      hd: "h",
                                                      tl: /* [] */0
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }), {
                                    TAG: /* Start */0,
                                    _0: 0
                                  }, maze)));
              }));
        Jest.test("all collected", (function (param) {
                return Jest.Expect.toEqual(/* [] */0, Jest.Expect.expect(Day18$Aoc19.Maze.nextKeys(Day18$Aoc19.KeySet.fromList({
                                        hd: "a",
                                        tl: {
                                          hd: "b",
                                          tl: {
                                            hd: "c",
                                            tl: {
                                              hd: "d",
                                              tl: {
                                                hd: "e",
                                                tl: {
                                                  hd: "f",
                                                  tl: {
                                                    hd: "g",
                                                    tl: {
                                                      hd: "h",
                                                      tl: {
                                                        hd: "i",
                                                        tl: {
                                                          hd: "j",
                                                          tl: {
                                                            hd: "k",
                                                            tl: {
                                                              hd: "l",
                                                              tl: {
                                                                hd: "m",
                                                                tl: {
                                                                  hd: "n",
                                                                  tl: {
                                                                    hd: "o",
                                                                    tl: {
                                                                      hd: "p",
                                                                      tl: /* [] */0
                                                                    }
                                                                  }
                                                                }
                                                              }
                                                            }
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }), {
                                    TAG: /* Start */0,
                                    _0: 0
                                  }, maze)));
              }));
        
      }));

Jest.describe("count of keys", (function (param) {
        return Jest.test("can count the keys", (function (param) {
                      return Jest.Expect.toBe(16, Jest.Expect.expect(Day18$Aoc19.Maze.numberOfKeys(maze)));
                    }));
      }));

Jest.describe("finds the shortest way to collect all keys", (function (param) {
        return Jest.test("can count the keys", (function (param) {
                      return Jest.Expect.toBe(136, Jest.Expect.expect(Day18$Aoc19.Maze.collectAllKeys(mazeString)));
                    }));
      }));

/* maze Not a pure module */
